# .bashrc

#export I3_PORTS=/Users/james/files/software/icecube/i3ports
#I3_SVN="http://code.icecube.wisc.edu/svn"
#export I3_SVN

export HISTFILESIZE=10000

#PERL_MB_OPT="--install_base \"/Users/james/perl5\""; export PERL_MB_OPT;
#PERL_MM_OPT="INSTALL_BASE=/Users/james/perl5"; export PERL_MM_OPT;

VIRTUAL_ENV_DISABLE_PROMPT=1
#. ~/.virtualenv/standard/bin/activate
. ~/.virtualenv/python37/bin/activate

export ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future

if [ -f ~/.bash_aliases ]; then
       source ~/.bash_aliases
fi

# Still thinking about this
if [ -f ~/.bash_functions ]; then
       source ~/.bash_functions
fi

export PATH=$HOME/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/prog/github/scripts/bin:$PATH

export HOMEBREW_GITHUB_API_TOKEN=905f3e859098e65f2b961fbad8d99898ee08481c
export EDITOR=/usr/local/bin/vim

#export PYTHONPATH=/usr/local/lib/python2.7:$PYTHONPATH


function offer_tmux
{
    read -p "Start Tmux ? [y/N] " start_tmux

    if  [[ $start_tmux == "y" || $start_tmux == "Y" ]]
    then
        tmux
    fi
}
[[ -z  $TMUX  ]] && offer_tmux


eval $(thefuck --alias)
