-- Treesitter settings

-- local configs = require'nvim-treesitter.configs'
-- configs.setup {
--     ensure_installed = {"c", "python", "lua", "bash", "latex" },
--     -- ensure_installed = {"maintained"},
--     highlight = { -- enable highlighting
--         enable = true,
--     },
--     indent = {
--         enable = false, -- default is disabled anyways
--     }
-- }
