# Config editing stuff
alias eb='vim $HOME/.bash_aliases'
alias sb='source $HOME/.bash_aliases'

alias es='vim $HOME/.ssh/config'
alias et='vim $HOME/.tmux.conf'

shopt -s autocd

# This has to be set early...
export PATH=$PATH:$HOME/.local/bin

[ -f ~/.ps1.env ] && source ~/.ps1.env
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

if command -v exa &> /dev/null; then
    alias ls='exa'
fi

if command -v batcat &> /dev/null; then
    alias cat='batcat'
fi

if command -v nvim &> /dev/null; then
    alias vim='nvim'
    alias v='nvim'
    alias vd='nvim -d'
    alias ev='vim $HOME/.config/nvim/lua/hanavi/init.lua'
    alias vv='/usr/bin/vim'
else
    alias v='vim'
    alias vd='vimdiff'
    alias ev='vim $HOME/.vim/vimrc'
fi

if command -v feh &> /dev/null; then
    alias f='feh -.'
fi

if command -v zathura &> /dev/null; then
    alias z="zathura"
fi

alias dh="du -hs"
alias ipy="ipython"
alias m='mplayer'

# Moving around
alias src='cd /usr/local/src/'
alias tmp='cd ~/tmp'
alias dfd="cd ~/files/dotfiles/"

if [ -d ~/.config/nvim/lua/hanavi ]; then
    alias ndir="cd ~/.config/nvim/lua/hanavi"
else
    alias ndir="cd ~/.vim/"
fi

# dropbox
if [ -d ~/.dropbox-dist ]; then
    alias db="~/.dropbox-dist/dropboxd &; disown"
    alias ds="ps aux | grep -i dropbox |grep -v grep"
fi

# redshift
if [ -x $HOME/scripts/run_redshift.sh ]; then
    alias rs="$HOME/scripts/run_redshift.sh &; disown"
    alias dr="ps aux | grep -i redshift |grep -v grep"
fi

## ls stuff
alias ll='ls -l'
alias la='ls -A'
alias l='ls -F'
alias lll='ls -alhF'
alias l.='ls -d .*'
alias lh='ls -alh'

## SSH
alias sa='ssh-add'
if [ "`hostname`" = "thinkpad" ]; then
    alias hl='ssh homelocal'
    alias hv1='ssh hv1'
    alias hv2='ssh hv2'
    alias pi7='ssh pi7'
fi

## Misc
alias tl='tmux ls'
alias ta='tmux attach'
alias kap="killall pinentry"

## Email
alias mmutt="zless /usr/share/doc/mutt/manual.txt.gz"
alias rmutt='ssh -X -t email "env LC_ALL=C.UTF-8 MUTT_CONFIG=fetchmail /usr/bin/mutt"'
alias amutt='ssh -X -t email "env LC_ALL=C.UTF-8 MUTT_CONFIG=aol /usr/bin/mutt"'
alias mm='ssh -X -t pi6 "/usr/bin/mutt"'

# webbrowser stuff
alias web="python -m webbrowser"
alias gnews='firefox --private-window -- http://news.google.com'
alias gmail='python -m webbrowser gmail.com'
alias xkcd='python -m webbrowser xkcd.com'

# docker
alias dr='docker run --rm -it'

# Check for up ssh systems
up() {
    nmap -n -oG - --open 192.168.1.0/24 -p 22 |grep Up | awk '{print $2}'
}

resetcard() {
    rm -r ~/.gnupg/private-keys-v1.d
    gpgconf --kill gpg-agent
    gpg --card-status
}

[ $TERM == "st-256color" ] && transset-df --id "$WINDOWID" .75 >/dev/null

export EDITOR=vim
export FCEDITOR=vim

# git

alias g=git
alias ga='git add'
alias gcmsg='git commit --message'
alias gst='git status'
alias gd='git diff'
alias gl='git pull'
alias gp='git push'
alias glg='git log --stat'
alias glgg='git log --graph'
alias glgga='git log --graph --decorate --all'
alias glgm='git log --graph --max-count=10'
alias glgp='git log --stat --patch'
alias glo='git log --oneline --decorate'
alias glod='git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset"'
alias glods='git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset" --date=short'
alias glog='git log --oneline --decorate --graph'
alias gloga='git log --oneline --decorate --graph --all'
alias glol='git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset"'
alias glola='git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset" --all'
alias glols='git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset" --stat'

